### ISSUE TITLE
Default value trouble: order

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/orbisdata#110]
The default value is now taken into account (#93). However, I got a problem in the following example:
```groovy
public static IProcess computeRSUIndicators() {
    return processFactory.create("Compute the geoindicators at block scale",
            [datasource                 : JdbcDataSource, buildingTable              : String,
             rsuTable                   : String,         prefixName                 : "rsu_indicators"],
[output: String],
{datasource, buildingTable, prefixName, rsuTable}
...
```
The prefixName and rsuTable are inverted in the closure and the default prefixName value is assigned to rsuTable. Is it a normal behaviour ? Then I have to verify that the inputs are in the same order in the declaration and in the closure ?

**Comment by SPalominos** [comment]
The inputs have to be is the same order than in the closure. There is no way to get the closure parameters name so no way to bind them.

**Comment by j3r3m1** [comment]
OK good to know that !
