### ISSUE TITLE
Index creation

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/orbisdata#113]
I have tried the commands you have proposed to create indexes on spatial tables and I got the following error message:
'No such property: the_geom for class: org.orbisgis.datamanager.h2gis.H2gisSpatialTable'

Here is what I have executed:
```groovy
H2gisSpatialTable rsuSpatialTable = datasource.getSpatialTable(rsuTable)
if(!(rsuSpatialTable[geometricColumnRsu].spatialIndexed)){
    rsuSpatialTable[geometricColumnRsu].createSpatialIndex()
```
Note that it is the same problem if I write rsuSpatialTable.the_geom and that I have performed a mvn clean install in a new terminal outside IntelliJ.

**Comment by SPalominos** [comment]
Do you have a more complete example with the table creation  ?

**Comment by j3r3m1** [comment]
OK it does work after a clean install of the maven dependencies (and a deletion of the orbisdata dependencies that have been modified).

In order to avoid the deletion of the maven cache for each new change in the orbisdata files, @SPalominos made me change the pom.xml or geoclimate (I have added "<updatePolicy>always</updatePolicy>" after line 146 within the snapshots section. Thus now dependencies are downloaded each time we will make a mvn clean install.

**Comment by SPalominos** [comment]
Great! I close the issue.
