### ISSUE TITLE
Add dataframe concept

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisdata#169]
Add the dataframe concept to the API on order to be able to implement/cover smile API in a dedicated module name `dataframe`

**Comment by j3r3m1** [comment]
For information, currently it seems there is nothing within smile that allow to convert a DataFrame to a JDBCTable. Thus to return a dataframe to a database, I have to save the dataframe as a csv and then import the csv into H2

**Comment by SPalominos** [comment]
Thank you for the feedback, I will dig to find how to make JdbcTable compatible with DataFRame and reverse.

**Comment by ebocher** [comment]
Add the following methods to the dataframe objet

- [ ] DataFrame.columns :  The column labels of the DataFrame.
- [ ] DataFrame.ndim | Return an int representing the number of axes / array dimensions.
- [ ] DataFrame.size | Return an int representing the number of elements in this object.
- [ ] DataFrame.isEmpty | Indicates whether DataFrame is empty.
- [ ] DataFrame.summary | Statistics on the values
