### ISSUE TITLE
Add pool mecanism

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisdata#171]
Add to the `IDataSource` classes pool mechanism.

**Comment by j3r3m1** [comment]
What does this imply to my current code ? For further information see my current branch https://github.com/j3r3m1/geoclimate-1/tree/randomForest

**Comment by SPalominos** [comment]
It won't change anything, the pool mechanism changes how the DataSource manage the connection in order to limit the resource consumption. Those change wont modify the behaviour of the DataSource.

**Comment by ebocher** [comment]
What about

```
@Grab('commons-dbcp:commons-dbcp:1.4')
import groovy.sql.Sql
import org.apache.commons.dbcp.BasicDataSource

def ds = new BasicDataSource(driverClassName: "org......jdbcDriver",
    url: 'jdbc:h2:mem:yourDB', username: 'sa', password: '')

H2GIS.open(ds)

```

**Comment by ebocher** [comment]
Fixed
