### ISSUE TITLE
ITable summary function

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisdata#178]
As for dataframe I propose to add the method summary on a ITable.
It would be useful to understand the data.

**Comment by SPalominos** [comment]
Two things : 
- In the smile API, the summary of a DataFrame returns a DataFrame, so I guess the `getSummary()` method on the `ITable` should return an `Object` or you have an other idea for the return type ?
- What should contains the summary of the Jdbc implementations of  `ITable` (`H2hisSpatialTable, JdbcTable ...) ?

**Comment by ebocher** [comment]
It will return a String representation with all statistics
