### ISSUE TITLE
Process Input type

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisdata#188]
It seems that if the input type is set using a java primitive. The process factory converts it to a JAVA object. In the following script the input int will return an Integer.
Is it possible to avoid this transformation ?

```java
IProcess createRandomForestClassif() {
    return create({
        title "Create a Random Forest model"
        inputs intType : int
        outputs className: String
        run { intType ->

          
        }
    })
```

**Comment by SPalominos** [comment]
For now it isn't possible as in background we are using `Collection` which can only take `Object` and Groovy wrap primitive type into `Numeric` ([more info here](https://groovy-lang.org/objectorientation.html#_primitive_types))

**Comment by ebocher** [comment]
Thanks
