### ISSUE TITLE
Set srid on spatial table

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisdata#194]
Add a method to set an srid on a spatial table

**Comment by SPalominos** [comment]
@ebocher, do you mean set the SRID on all the geometric columns of a table ? or on a specific column ?

**Comment by SPalominos** [comment]
`JdbcSpatialTable.srid = 4326` apply the SRID on the very first geometric column.
`JdbcSpatialTable.column(...).srid = 4326` apply the SRID on the column
