### ISSUE TITLE
Move methods into parent classes.

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisdata#217]
List of methods to put in the ISpatialTable or ITable :
- columns()
- filter() (instead of where())
- getDouble
- getInt
- getString
- get...

**Comment by ebocher** [comment]
getObject(index, Boolean.class), getObject(index, Double.class). ...

**Comment by ebocher** [comment]
Done ?

**Comment by SPalominos** [comment]
No completely, an other PR is coming.
