### ISSUE TITLE
Statement context

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisdata#255]
Add a way  to customize the statement context  : 
``` java
ResultSet.TYPE_FORWARD_ONLY
ResultSet.CONCUR_UPDATABLE
ResultSet.CONCUR_READ_ONLY
```

**Comment by SPalominos** [comment]
A proposal :
The idea is to use a a builder (same idea as in the issue #263)
Option : 
 - type() : The resultset type which can be one of FORWARD_ONLY, SCROLL_INSENSITIVE, SCROLL_SENSITIVE
 - concurrency() : The resultset concurrency which can be one of : READ_ONLY, UPDATTABLE
 - holdability() : The resultset holdability which can be one of : HOLD_CIRSOR_OVER_COMMIT, CLOSE_CURSOR_AT_COMMIT
#### Methods coming from `statement`
 - direction() : The fetch direction wich can be FORWAR, REVERSE, UNKNOWN
 - size() : The fetch size
 - timeout() : The query timeout
 - maxRow() : the query result max row
 - cursorName() : the name of the cursor used for positioned update/delete
 - poolable() : Request the statement be poolable like `PrepareStatement`
 - maxFieldSize() : The maximum size of a return field. Only apply to those types : Binary, VarBinary, LongVarBinary, Char, VarChar, NChar, NVarChar, LongVarChar, LonNVarChar.

**Comment by ebocher** [comment]
Fixed thanks
Statement context must now used by all methods
see https://github.com/orbisgis/orbisdata/issues/292
