### ISSUE TITLE
DSL for IO methods

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisdata#263]
Proposal for save file

ISpatialTable.save("/myFile.json").encoding(charset).delete();
-> Save into a file
-> delete delete output file if exists
-> encoding charset

ISpatialTable.save("/myFile.json").encoding(charset).gz().delete();
-> Save into a file
-> delete delete output file if exists
-> encoding charset
-> gz compress the file in myFile.gz

ISpatialTable.save("/myFile.json").encoding(charset).zip().delete();
-> Save into a file
-> delete delete output file if exists
-> encoding charset
-> zip compress the file in myFile.zip

**Comment by ebocher** [comment]
Proposal for load file

h2gis.load("/myFile.json").encoding(charset).delete();
-> Load into a file
-> delete delete table file if exists
-> encoding charset

h2gis.load("/myFile.json").name("tableName").encoding(charset).delete();
-> Load into a file
-> delete delete table file if exists
-> encoding charset
-> name name of the imported file

**Comment by ebocher** [comment]
Todo  :  
Find a syntax for batch load, save and link at JDBCDatasource level.
e.g. h2gis.batchSave{....}

**Comment by SPalominos** [comment]
### Syntax
The is a limitation, it should follow this pattern :
```java
SpatialTable.firstMethod().what().you().want().lastMethod()
```
In the examples, the `firstMethod()` is `save()` or `load()` but for the `lastMethod()` which is triggering the save/load we have nothing as `delete()`, `encoding()` and `name()` are optional.

maybe we could have this syntax : 
```groovy
SpatialTable.save().encoding("UTF-8").delete() as Json
//OR
SpatialTable.encoding("UTF-8").delete().save("json")
SpatialTable.delete().encoding("UTF-8").save("json")
```

I have my own preference for the first syntax.

### Batch
For batch load, we could write in java :
``` java
 h2gis.batchSave(String[] tableNames).encoding(..)...
```
and with Groovy batchSave or the Spread-dot Operator :
``` groovy
h2gis.batchSave(String[] tableNames).encoding(..)...
//OR
def tables = [table1, table2, table3]
tables*.save().encoding(...)...
```

**Comment by SPalominos** [comment]
List of way to use it :

- Save a Table in a folder (format (json, csv ...) but no name provided/compression)
- Save a Table in a folder and compress it (format (json, csv ...) and compression but no name provided)
- Save a Table in a file (format (json, csv ...) but no compression)
- Save a table in a compressed file (format (json, csv ...) and compression)

**Comment by ebocher** [comment]
So in action we will have

For a folder
```

getTable("orbisgis").folder("/tmp/").json()
output -> /tmp/orbisgis.json

getTable("orbisgis").folder("/tmp/").ut8().json()
output -> /tmp/orbisgis.json with udt8 encoding

getTable("orbisgis").folder("/tmp/").gz().json()
output -> /tmp/orbisgis.gz  with inside a json file

getTable("orbisgis").folder("/tmp/").zip().json()
output -> /tmp/orbisgis.zip  with inside a json file

Note that the shp and dbf drivers don't support compression

getTable("orbisgis").folder("/tmp/").name("h2gis").json()
output -> /tmp/h2gis.json  name is used to rename the file name

getTable("orbisgis").folder("/tmp/").delete().json()
output -> /tmp/orbisgis.json delete the output file if exists

```

For a file
```

getTable("orbisgis").file("/tmp/orbisgis.json").save()
output -> /tmp/myjson.json"

getTable("orbisgis").file("/tmp/orbisgis.json").utf8().save()
output -> /tmp/orbisgis.json with udt8 encoding

getTable("orbisgis").file("/tmp/orbisgis.json").gz().save()
output -> /tmp/orbisgis.gz  with inside a json file

getTable("orbisgis").file("/tmp/orbisgis.json").gz().save()
output -> /tmp/orbisgis.zip  with inside a json file

Note that the shp and dbf drivers don't support compression

```
Is this approach better than one method with many arguments

getTable("orbisgis").save("/tmp/orbisgis.json")

getTable("orbisgis").save("/tmp/orbisgis.json.gz")

getTable("orbisgis").save("/tmp/orbisgis.json.gz", encoding, deletefile)...

@j3r3m1 @gpetit @ELSW56

**Comment by j3r3m1** [comment]
Impossible for me to simply remember if the first solution is adopted, I really prefer the second one with save(several arguments). Is the first one is getting a common way of doing ?

**Comment by ebocher** [comment]
After a call conf, we decided to not use a DSL but the save method with arguments
Some modifications must be done on H2GIS side to detect if content of the compressed file, using https://commons.apache.org/proper/commons-compress/

**Comment by ebocher** [comment]
This issue can be closed because we decided to add methods in H2GIS and then in OrbisDATA to zip and unzip.
So the user must do the job himself and then play with the load and save methods
