### ISSUE TITLE
Load from db to db

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisdata#270]
This is for a new feature demand

``` java
datasource1.load(datasource2, tableName, deleteIfExsits)
```

**Comment by j3r3m1** [comment]
I would also set a parameter for the name of the table in datasource1. Like when we load a table from a file.

**Comment by ebocher** [comment]
What about
datasource1.getTable('tata'). load(datasource2, tableName, deleteIfExsits)

**Comment by ebocher** [comment]
or
 datasource1.getTable('tata'). export(datasource2, tableName, deleteIfExsits)

**Comment by j3r3m1** [comment]
The advantage of the third solution is that it is a new function (export). The disadvantage is that it is less obvious than the load keyword. But the second solution differs from what we are used to (datasource.load).
What about datasource1.load(tableDatasource2, tableName, deleteIfExist) with tableDatasource2 the table to import from the datasource2 ?

**Comment by ebocher** [comment]
So in fine we will have

 datasource1.getTable('tata'). save(datasource2, [tableName, deleteIfExsits]) [ ] = options

 datasource1.load(datasource2,tableName,  [deleteIfExsits]) [ ] = options

**Comment by j3r3m1** [comment]
OK for save. Concerning load, maybe it would be preferable to let the option to load the table using a different name ? Because the table in datasource2 may have the same name as a table in datasource1 but we may want to keep both of them in datasource1 (for comparison for example)

**Comment by ebocher** [comment]
Add also on dataframe

**Comment by ebocher** [comment]
add batch size argument on save

**Comment by ebocher** [comment]
I'm on the load method

**Comment by ebocher** [comment]
So we have now the following syntax :  

```
h2GIS.getSpatialTable("myTable").save(postgisDB, true)) -> Save from H2GIS to PostGIS and drop the input table if exists
postgis.load(h2GIS, "myTable", true) -> Load from H2GIS to PostGIS and drop the input table if exists

```

**Comment by j3r3m1** [comment]
What about the problem of potential name conflict ? Is there an option to rename "myTable" into "myTableNewName" in the new datasource ?
> OK for save. Concerning load, maybe it would be preferable to let the option to load the table using a different name ? Because the table in datasource2 may have the same name as a table in datasource1 but we may want to keep both of them in datasource1 (for comparison for example)

**Comment by ebocher** [comment]
If the table already exists it returns an error message and null. It's the same behaviour for the link and save from file methods

**Comment by j3r3m1** [comment]
OK so let's imagine I have a table called "toto" in my H2 DB and also in my POSTGIS and I want to import the one from postGIS into H2 I should first rename the table either in postgis or either in H2 and then import it ?

**Comment by ebocher** [comment]
You can do that : 

postgis.load(h2GIS, "toto","the_new_table_name")

**Comment by j3r3m1** [comment]
that would be nice indeed. And same for exporting

**Comment by ebocher** [comment]
Done
