### ISSUE TITLE
Check if netlib is not used by OrbisDATA and Geoclimate

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisdata#286]

**Comment by SPalominos** [comment]
The netlib dependencies are declared as dependencies in the `smile-core` artifact so they are downloaded by default.

**Comment by ebocher** [comment]
What about excluding this dep with maven ?

**Comment by ebocher** [comment]
Issue on Smile repo https://github.com/haifengl/smile/issues/580

**Comment by ebocher** [comment]
Fixed thanks to @haifengl

**Comment by ebocher** [comment]
Doesn't work

**Comment by SPalominos** [comment]
I'm on it
