### ISSUE TITLE
ResulsetBuilder in JDBCDatasource vs getTable in database implementation

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisdata#292]
ResulsetBuilder has been introduced to support fetch and other methods on statement.
getTable in ResulsetBuilder is able to build a new resulset either from a table name or query (specified by parenthesis).
ResulsetBuilder is used in JDBCDatasource in order to execute statement as executeBatch, executeLargeUpdate)

From database implementation like H2GIS  the getSpatialTable works only with table name ?

This architecture seems a bit strange.

**Comment by ebocher** [comment]
Note that in the  BuilderResult a new statement is instantiated in asType method
So in the case of
postgis.forwardOnly().readOnly().holdCursorOverCommit().fetchForward()
                .fetchSize(SIZE).timeout(TIMEOUT).maxRow(MAX_ROW).cursorName("name").poolable()
                .maxFieldSize(FIELD_SIZE).getTable("test_postgis").columns("the_geom").filter("limit 1");
the statement configuration will not be used.

**Comment by ebocher** [comment]
I reopened this issue because h2gis and postgis getTable and getSpatialTable do not use the ResulsetBuilder statement conf.
see https://github.com/orbisgis/orbisdata/blob/master/data-manager/jdbc/src/main/java/org/orbisgis/orbisdata/datamanager/jdbc/h2gis/H2GIS.java#L301

**Comment by SPalominos** [comment]
In fact, the `ResulsetBuilder` have its custom implementation of [`getTable(String)`](https://github.com/orbisgis/orbisdata/blob/master/data-manager/jdbc/src/main/java/org/orbisgis/orbisdata/datamanager/jdbc/dsl/ResultSetBuilder.java#L325) which uses the generated `Statement`. 
In `H2GIS` and `POSTGIS` there is also a method `getTable(String, Statement)` which allow to customize the `Statement` used.
I'm doing a PR to avoid code duplication and to make `ResultSetBuilder` use the `getTable()` methods from the datasources but we are already using the `ResultSetBuilder` generated `Statement`.

**Comment by ebocher** [comment]
Thanks
