### ISSUE TITLE
Filter subquery bug

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisdata#303]
The following code 
```java
getTable("postgis").columns("id").filter("limit 2").getTable().filter("where id=2").getTable()
```
build the string query : 

SELECT * FROM (SELECT id FROM postgis limit 2) where id=2

But the subquery in FROM must have an alias as  : 

SELECT * FROM (SELECT id FROM postgis limit 2) as foo  where id=2

Another example : 

SELECT *  FROM (SELECT * FROM (SELECT id FROM postgis limit 2) as foo  where id=2) )AS foo

**Comment by SPalominos** [comment]
Th PR #304 is a very simple fix, but the issue should stay open until a better solution is found.
