### ISSUE TITLE
.gz not loadable yet ?

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/orbisdata#312]
It seems that we can not use orbisdata to read the .gz yet ?

https://github.com/orbisgis/orbisdata/blob/85b944356efd1fbc7a40bbe0a09792bda46f591e/data-manager/jdbc/src/main/java/org/orbisgis/orbisdata/datamanager/jdbc/io/IOMethods.java#L107

**Comment by ebocher** [comment]
Fixed
