### ISSUE TITLE
Rework modules architecture

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisdata#348]
The module API is kept.
The module jdbc will only keep classes common to each database.
Modules H2/H2GIS and Postgresql/Postgis will be created.

**Comment by ebocher** [comment]
After a Suisse meeting about SymCore, Feature2DTypeStyle model, OrbisMap and @baremaps team, we decided to 

- simplify all orbisdata artifact and package names. e.g org.orbisgis.orbisdata.datamanager.jdbc.h2gis will replaced by org.orbisgis.jdbc.h2gis
- use jsqlparser to prepare and analyse the sql queries send to the JDBC client
- clean the orbisdata api and isolate it in a module called org.orbisgis.data-api.
- add a dialect mechanism for all jdbc providers (h2gis, postgis...)

These tasks must be done asap.

**Comment by ebocher** [comment]
This is a proposal to simplify the name of the artifacts and packages before the next release

<groupId>org.orbisgis.orbisdata.datamanager</groupId> to <groupId>org.orbisgis.data</groupId>

So we will have

```
 <dependency>
                <groupId>org.orbisgis.data</groupId>
                <artifactId>data-api</artifactId>
                <version>${version}</version>
            </dependency>

 <dependency>
                <groupId>org.orbisgis.data</groupId>
                <artifactId>jdbc</artifactId>
                <version>${version}</version>
 </dependency>

 <dependency>
                <groupId>org.orbisgis.data</groupId>
                <artifactId>process-api</artifactId>
                <version>${version}</version>

 <dependency>
                <groupId>org.orbisgis.data</groupId>
                <artifactId>process</artifactId>
                <version>${version}</version>
</dependency>

 <dependency>
                <groupId>org.orbisgis.data</groupId>
                <artifactId>dataframe</artifactId>
                <version>${version}</version>
</dependency>
```
And then in Groovy
@Grab(group='org.orbisgis.data', module='jdbc', version='1.0.1-SNAPSHOT')

@j3r3m1

**Comment by ebocher** [comment]
done
