### ISSUE TITLE
OrbisProcess trouble

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/orbisdata#48]
@ebocher @SPalominos 
I have started to code indicators using the OrbisProcess syntax and I am currently facing several problems (you can find the entire code at the end of the message):

1. I code in the Groovy console within the OrbisGIS plat-form and when I run my code, the script is executed but nothing is actually performed. I have tried to print random words at the beginning of the script and they appear only if I remove the following lines:
`import org.orbisgis.datamanager.h2gis.H2GIS`

2. I do not know what is the expected method to use SQL queries within the OrbisProcess. I have tried two different versions (in "process1" I recover the database from the input ITable whereas in "process2" I pass the database and the Table name as inputs. What do you think would be the best solution ?

``` groovy
// The OrbisData library is imported
@GrabResolver(name='orbisgis', root='http://repo.orbisgis.org/')
@Grab(group='org.orbisgis', module='data-manager', version='1.0-SNAPSHOT')

// The H2Gis module is also imported
import org.orbisgis.datamanager.h2gis.H2GIS



// Create the tables needed to test the functions
def h2GIS = H2GIS.open([databaseName: './target/loadH2GIS'])
h2GIS.execute("""
     DROP TABLE IF EXISTS building_test;
     DROP TABLE IF EXISTS rsu_test;
     CREATE TABLE building_test (id_build int, the_geom geometry, height_wall float, height_roof float);
     CREATE TABLE rsu_test (id_rsu int, the_geom geometry);
     INSERT INTO building_test VALUES (1, 'POLYGON((4 4, 10 4, 10 30, 4 30, 4 4))'::GEOMETRY, 8), (2, 'POLYGON((12 4, 20 4, 20 9, 12 9, 12 4))'::GEOMETRY, 10), (3, 'POLYGON((25 4, 45 4, 45 9, 25 9, 25 4))'::GEOMETRY, 8), (4, 'POLYGON((25 25, 40 25, 40 37, 25 37, 25 25))'::GEOMETRY, 5), (5, 'POLYGON((12 25, 25 25, 25 35, 12 35, 12 25))'::GEOMETRY, 12), (6, 'POLYGON((52 2, 54 2, 54 10, 52 10, 52 2))'::GEOMETRY, 15);
     INSERT INTO rsu_test VALUES (1, 'POLYGON((0 0, 50 0, 50 40, 0 40, 0 0))'::GEOMETRY), (2, 'POLYGON((50 0, 55 0, 55 30, 50 30, 50 0))'::GEOMETRY);
""")

def process1 = processFactory.create(
      "Building area without SQL passed",
      [inputA: ITable, inputB: String, inputC: String, inputD: String],
      [outputA : ITable],
      { inputA, inputB, inputC, inputD -> 
      // Recover the DataBase where is located the inputA Table
      sql = inputA.getDataBase()
      // Recover the name of the input Table in order to be used in the SQL queries
      inputA_name = inputA.getTableName()    // Note that I have not found any function to get the Table name...
      // Calculate the value of the indicator and store it in a new Table
      sql.execute("create table $inputB as select $inputD, st_area($inputD) as $inputC from $inputA_name")
      [outputA : sql.getSpatialTable("$inputA_name")] }
)

process1.execute([inputA: h2GIS.getSpatialTable("building_test"), inputB: "building_area", inputC: "building_area", inputD: "the_geom"])

def process2 = processFactory.create(
      "Building area with SQL passed",
      [inputA: String, inputB: String, inputC: String, inputD: String, inputE: Database],
      [outputA : ITable],
      { inputA, inputB, inputC, inputD, inputE -> 
      // Calculate the value of the indicator and store it in a new Table
      inputE.execute("create table $inputB as select $inputD, st_area($inputD) as $inputC from $inputA")
      [outputA : inputE.getSpatialTable("$inputB")] }
)

process2.execute([inputA: "building_test", inputB: "building_area", inputC: "building_area", inputD: "the_geom", inputE: h2GIS])
```

**Comment by ebocher** [comment]
Thanks @j3r3m1. Indeed, there are several usages that we need to clarify.
In your case, here is my proposal : 

inputA = ITable
We want to query the table and return a new ITable
Because ITable is a resulset (a table from a database), we'd be nice to offer a way to get the parent JdbcDataSource so the user can do
 inputA.getDataSource() return the H2GIS or PostGIS objects
and then
 inputA.getDataSource().execute "create table ...." or

perhaps
inputA.getDataBase() must renamed to getdbtype or db name closed to the JDBC Driver Vendor. The name of the method is not sufficiently clear.

**Comment by ebocher** [comment]
@SPalominos

**Comment by j3r3m1** [comment]
Thank you both for replying.

@SPalominos 
Question 1:
I have tried the code in the official groovy console. After several modifications (note that one of them is that I got rid of the Grab annotations), it works well. I would like to use this modified script in OrbisGIS since it would be easier to test sql queries and manipulate the tables then. However, when I run it in the OrbisGIS Groovy console, I get an error at the import lines (unable to resolve class...).
Is there a way to resolve the dependencies without Grab ?

@SPalominos @ebocher 
Question 2:
It seems that you do not have the same opinion concerning this point. My first solution (ITable as input and output) do not work because I do not know how to get a table name. Then I have only tested the second solution (ITable names as input and output and Database as input) which works well and is clear enough from my user point of view.
However, in order to test whether my process works well, I wanted to print the geometries of my output ISpatialTable but the result of my getGeometry() is null, where am I mistaken ?

Here is the updated code (which works well but only the official groovy console):
```groovy
package org.orbisgis.processmanager

// The H2Gis module is also imported
import org.orbisgis.datamanager.h2gis.H2GIS
import org.orbisgis.datamanagerapi.dataset.ITable;
import org.orbisgis.datamanagerapi.dataset.Database;

final ProcessFactory processFactory = new ProcessFactory()

// Create the tables needed to test the functions
def h2GIS = H2GIS.open([databaseName: '/tmp/loadH2GIS'])
h2GIS.execute("""
-- SQL script used to create the building and reference spatial unit (RSU) Tables that will be used to test the validity of the indicators.
-- Note that all fields respect the generic names defined within the PAENDORA and URCLIM projects.
-- Each RSU contains one or several buildings having different vertical and horizontal sizes.

     DROP TABLE IF EXISTS building_test;
     DROP TABLE IF EXISTS rsu_test;
     CREATE TABLE building_test (id_build int, the_geom geometry, height_wall float, height_roof float);
     CREATE TABLE rsu_test (id_rsu int, the_geom geometry);
     INSERT INTO building_test VALUES (1, 'POLYGON((4 4, 10 4, 10 30, 4 30, 4 4))'::GEOMETRY, 8, null), (2, 'POLYGON((12 4, 20 4, 20 9, 12 9, 12 4))'::GEOMETRY, 10, 13), (3, 'POLYGON((25 4, 45 4, 45 9, 25 9, 25 4))'::GEOMETRY, 8, 14), (4, 'POLYGON((25 25, 40 25, 40 37, 25 37, 25 25))'::GEOMETRY, 5, null), (5, 'POLYGON((12 25, 25 25, 25 35, 12 35, 12 25))'::GEOMETRY, 12, 12), (6, 'POLYGON((52 2, 54 2, 54 10, 52 10, 52 2))'::GEOMETRY, 15, 18);
     INSERT INTO rsu_test VALUES (1, 'POLYGON((0 0, 50 0, 50 40, 0 40, 0 0))'::GEOMETRY), (2, 'POLYGON((50 0, 55 0, 55 30, 50 30, 50 0))'::GEOMETRY);
""")

def process2 = processFactory.create(
      "Building area with SQL passed",
      [inputA: String, inputB: String, inputC: String, inputD: String, inputE: Database],
      [outputA : ITable],
      { inputA, inputB, inputC, inputD, inputE -> 
      // Calculate the value of the indicator and store it in a new Table
      
      inputE.execute("DROP TABLE IF EXISTS $inputB; CREATE TABLE $inputB AS SELECT $inputD, ST_AREA($inputD) AS $inputC FROM $inputA".toString())
      [outputA: inputB] }
)

process2.execute([inputA: "building_test", inputB: "building_area", inputC: "building_area", inputD: "the_geom", inputE: h2GIS])
print h2GIS.getSpatialTable(process2.getResults().outputA).getGeometry("the_geom")
```

**Comment by ebocher** [comment]
If the second approach is ok for you  that enough for me.
Concerning your question  about  printing the geometries.
outputA is waiting for a ITable and you set a String value
Try to replace   [outputA : String]

**Comment by j3r3m1** [comment]
There is no change, I still get null whereas 
``` groovy
print h2GIS.getSpatialTable(process2.getResults().outputA)
```
gives a SpatialITable (the result of my query is "org.orbisgis.datamanager.h2gis.H2gisSpatialTable@17cf2e7e")

**Comment by SPalominos** [comment]
@j3r3m1 
I will test how deals with grab on the OrbisGIS Groovy console and I will tell you about as soon as I have anything new. Same thing for your script, I will test it and look for what is going wrong.
@ebocher 
That the point, jdbcDataSource is used for the where filtering on an existing `ITable`. Filtering an existing table makes sens, it's like creating kind of a "sub" table. But creating a new table from an existing one which doesn't have anything in common seems to be a very strange behaviour.

**Comment by ebocher** [comment]
@j3r3m1 
println h2GIS.getTableNames() -> Shows that the table is created
to retrieve the geometry you must iterate over the resultset like this
h2GIS.getSpatialTable(process2.getResults().outputA.toUpperCase()).eachRow { row -> println row.getGeometry("the_geom")}

**Comment by SPalominos** [comment]
Issue moved to orbisgis/orbisgis#1352
