### ISSUE TITLE
DataSource.getSpatialTable("...") + Where condition architecture question

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisdata#49]
DataSource.getSpatialTable("...") -> Create a resultset

DataSource.getSpatialTable("...") where "..."  -> Create a resultset

So it seems two resultsets are opened to apply a where clause.

Right ?

**Comment by SPalominos** [comment]
Yes !

**Comment by ebocher** [comment]
So we must find to shortcircuit the first resultset.

Perhaps a delegate method as ITableWrapper

DataSource.getSpatialTable("...") -> do nothing

DataSource.getSpatialTable("...").eachRow, foreach -> Creat the resultset 

DataSource.getSpatialTable("...") where "..." -> Create a resultset

**Comment by SPalominos** [comment]
Ok, I will make a PR about that.

**Comment by ebocher** [comment]
thanks a lot

**Comment by ebocher** [comment]
Not sure if this issue is solved, so I reopened it.

h2GIS.getSpatialTable("routes") -> Create a resulset

h2GIS.getSpatialTable("routes")..limit(10) -> Create a resulset
