### ISSUE TITLE
Compile with java 8

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisdata#55]
Returns
intelij error:java:invalid target release:11

@j3r3m1

**Comment by SPalominos** [comment]
OrbisData should be compiled with java 11 in order to be compatible with the other modules (orbisFX, framework) but the release is for java 8. So jdk (javac) 11 and jre (java) 8.

**Comment by ebocher** [comment]
Ok thanks
Because OrbisData is not related to any GUI. It would be nice to support java 8 at compile time.

**Comment by j3r3m1** [comment]
I confess that if it is not so complicated for you to make it work it work with JDK 8 it would be brilliant since it seems that I need to upgrade my ubuntu version (17.04) to 18.04 to get JAVA 11. I will do that soon anyway but I had not planned to do that this week.

**Comment by SPalominos** [comment]
@j3r3m1 The changes on the `framework` and `orbisdata` library are done, can you try to compile the very last version of orbisdata with java 8 ?

**Comment by j3r3m1** [comment]
OK thank you, everything works fine now.
