### ISSUE TITLE
The method expression

### ISSUE THREAD

**Issue by Vquillien** [orbisgis/orbisdata#6]
This method is recursive on the type Function. It separate the different type of expression : Function, ValueReference, Literal and Object. 

For the type object, there are problems because there aren't any solution to know the structure of the type.
The only solution was that we add a condition for each type that we can find. Example: the GML.

**Comment by ebocher** [comment]
Sorry I don't understand.

**Comment by Vquillien** [comment]
I created a method "expression" in the pull request #7 , but in the last condition "else", there is only an Object.toString. At line, 386-388, I don't know how I have to manage the return in the variable stringBuilder. 
` }else{
         stringBuilder.append(" "+element.getValue().toString()+" ");
  }`

**Comment by SPalominos** [comment]
For now you should let it as not implemented case and just log a message telling that the expression is not recognized.
