### ISSUE TITLE
Method to check column names and datatype

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisdata#69]
This is a proposal to implement a method to check if a column exists and its type.

h2GIS.getSpatialTable("mytable").exists(THE_GEOM:GEOMETRY, ID : String)

the_geom -> Column name
Geometry -> Column type

@SPalominos

**Comment by SPalominos** [comment]
What do you think of `hasColumn(THE_GEOM:GEOMETRY, ID : String)` method name ?

**Comment by ebocher** [comment]
thx
