### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisdata#75]
Increase the coverage of :
  - [data-manager](https://devs.orbisgis.org/orbisdata/data-manager/jacoco/index.html)
  - [process-manager](https://devs.orbisgis.org/orbisdata/process-manager/jacoco/index.html)

and duplicate the test in groovy

**Comment by ebocher** [comment]
Seems fixed ?

**Comment by SPalominos** [comment]
Not until reached 100% of coverage ;)
