### ISSUE TITLE
ProcessMapper javadoc

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisdata#92]
Add doc, especially here
https://github.com/orbisgis/orbisdata/blob/master/process-manager/src/main/java/org/orbisgis/processmanager/ProcessMapper.java#L69

**Comment by ebocher** [comment]
Also for alias

**Comment by SPalominos** [comment]
Process mapper will be reworked to make the syntax easier like:
``` groovy
link pA.out1 to pB.in2 and pC.in1
link pA.in1 and pB.in1 and pC.in3 to inputs as "database"
link pB.out1 to outputs as "tableName"
link pA.out1 to outputs as "rowCount"
```
